# permissions for end users to edit memcachedclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcachedcluster-editor-role
rules:
- apiGroups:
  - memcached.luizbafilho.dev
  resources:
  - memcachedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - memcached.luizbafilho.dev
  resources:
  - memcachedclusters/status
  verbs:
  - get
